import { randomBytes } from "node:crypto";
import { dirname } from "node:path";
import {
  LocalYdbApiClient,
  bash,
  shellQuote,
  type CommandResult,
} from "../api-client.js";
import { redactText } from "../auth.js";
import { confirmationScopedId } from "../confirmation.js";
import { pathRedactions } from "../redactions.js";
import { runMutating } from "./execution.js";
import type {
  MutatingOptions,
  OperationResponse,
  ToolkitContext,
} from "./types.js";

const COMPOSITE_AUTH_PATH_PREFIX = "/tmp/local-ydb-toolkit-composite-auth-";

export const COMPOSITE_AUTH_CLEANUP_FAILURE = "Private composite auth artifacts could not be removed.";

export interface CompositeAuthArtifacts {
  context: ToolkitContext;
  persist(options: MutatingOptions): Promise<OperationResponse>;
  redact(text: string): string;
  redactResults(results: CommandResult[]): void;
  remove(): Promise<boolean>;
}

export function createCompositeAuthArtifacts(
  confirmationContext: ToolkitContext,
  executionContext: ToolkitContext,
  rotatingScope: unknown,
): CompositeAuthArtifacts {
  const scopedId = confirmationScopedId(confirmationContext, rotatingScope)
    ?? randomBytes(16).toString("base64url");
  const privateRoot = `${COMPOSITE_AUTH_PATH_PREFIX}${scopedId}`;
  const privateAuthConfigPath = `${privateRoot}/config.yaml`;
  const privateDynamicTokenPath = `${privateRoot}/dynamic-token.txt`;
  const privateRootPasswordPath = `${privateRoot}/root.password`;
  const profile = {
    ...executionContext.profile,
    authConfigPath: privateAuthConfigPath,
    dynamicNodeAuthTokenFile: privateDynamicTokenPath,
    rootPasswordFile: privateRootPasswordPath,
  };
  const context: ToolkitContext = {
    ...executionContext,
    profile,
    client: new LocalYdbApiClient(profile, executionContext.client.executor),
  };
  const canonical = confirmationContext.profile;
  const canonicalAuthConfigPath = canonical.authConfigPath;
  const canonicalDynamicTokenPath = canonical.dynamicNodeAuthTokenFile;
  const canonicalRootPasswordPath = canonical.rootPasswordFile;
  if (!canonicalAuthConfigPath || !canonicalDynamicTokenPath || !canonicalRootPasswordPath) {
    throw new Error("Composite auth artifacts require all configured auth paths.");
  }
  const redactions = pathRedactions(
    privateRoot,
    privateAuthConfigPath,
    privateDynamicTokenPath,
    privateRootPasswordPath,
    canonicalAuthConfigPath,
    canonicalDynamicTokenPath,
    canonicalRootPasswordPath,
  );
  const redact = (text: string) => redactText(text, redactions);

  return {
    context,
    persist: (options) => runMutating(context, {
      summary: "Persist generated auth artifacts after private preparation.",
      risk: "high",
      specs: [bash([
        "set -euo pipefail",
        "umask 077",
        `[ -f ${shellQuote(privateAuthConfigPath)} ]`,
        `[ -f ${shellQuote(privateDynamicTokenPath)} ]`,
        `[ -f ${shellQuote(privateRootPasswordPath)} ]`,
        `install -d -m 0700 ${shellQuote(dirname(canonicalAuthConfigPath))}`,
        `install -d -m 0700 ${shellQuote(dirname(canonicalDynamicTokenPath))}`,
        `install -d -m 0700 ${shellQuote(dirname(canonicalRootPasswordPath))}`,
        `cat ${shellQuote(privateAuthConfigPath)} > ${shellQuote(canonicalAuthConfigPath)}`,
        `cat ${shellQuote(privateDynamicTokenPath)} > ${shellQuote(canonicalDynamicTokenPath)}`,
        `cat ${shellQuote(privateRootPasswordPath)} > ${shellQuote(canonicalRootPasswordPath)}`,
        `chmod 0600 ${shellQuote(canonicalAuthConfigPath)} ${shellQuote(canonicalDynamicTokenPath)} ${shellQuote(canonicalRootPasswordPath)}`,
      ].join("\n"), {
        timeoutMs: 60_000,
        description: "Persist privately generated auth artifacts",
        redactions,
      })],
      rollback: ["Restore the previous host auth artifacts from a trusted backup."],
      verification: ["The configured auth artifact files contain the privately generated bytes."],
    }, options),
    redact,
    redactResults: (results) => {
      for (const result of results) {
        result.command = redact(result.command);
        result.stdout = redact(result.stdout);
        result.stderr = redact(result.stderr);
      }
    },
    remove: async () => {
      try {
        const result = await context.client.run(bash(`rm -rf ${shellQuote(privateRoot)}`, {
          timeoutMs: 60_000,
          description: "Remove private composite auth artifacts",
          redactions: pathRedactions(privateRoot),
        }));
        return result.ok;
      } catch {
        return false;
      }
    },
  };
}
